### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by AbdullahAli** [zoonooz/PolyImageView#1]
How can I use this please?  I want to have an image, but every time the image is not displayed (only background shown in the polygon)

Can you please post how you would use this from the ViewController? I looked at your blog post but that didn't help with this either.

This is how im using it:

```
var v = PolyImageView(frame: CGRectMake(30, 30, 300, 300))
v.imageView.image = UIImage(named: "image")
```

This is what I get:
![screen shot 2015-06-25 at 16 07 19](https://cloud.githubusercontent.com/assets/1620134/8357729/48fb55ce-1b54-11e5-927d-70c8be13d3e2.png)

Thank you

**Comment by zoonooz** [comment]
Hi @AbdullahAli 

Seems like I missed `setup()` in

```
override init(frame: CGRect) {
        super.init(frame: frame)
}
```

Sorry.

**Comment by AbdullahAli** [comment]
you are awesome! thanks :+1: @zoonooz
